In [1]:
import numpy as np

In [3]:
assign_1=np.array([0,1,2,3,4,5,6,7,8])

In [4]:
assign_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
output=assign_1.reshape(3,-1)
print(output)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
assign_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
assign_2[assign_2%2!=0]=-1
print(assign_2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [12]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])


In [14]:
greater=np.where(x>y)[0]
equal=np.where(x==y)[0]
print(greater)
print(equal)

[1 2 4 5 6 7 8 9]
[0]


In [16]:
Assign_4= np.arange(100).reshape(5,-1)

In [17]:
output = Assign_4[:, :4]
print(output)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [30]:
output=np.random.randint(30,40,size=10)

In [31]:
print(output)

[36 35 33 30 31 38 37 31 34 32]


In [32]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[7, 8, 10], [4, 5, 6], [1, 2, 3]])

In [33]:
C=A+B
E=A-B

In [35]:
C

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [36]:
E

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  7]])

In [37]:
sum_A=np.sum(A)

In [38]:
sum_A

46

In [39]:
sum_column_B=np.sum(B,axis=0)

In [40]:
sum_column_B

array([12, 15, 19])

In [41]:
sum_row_C=np.sum(C,axis=1)
sum_row_C

array([31, 30, 31])

In [42]:
D=np.dot(A,B)

In [43]:
D

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [44]:
E=np.sort(C,axis=None)

In [49]:
E


array([ 8,  8,  8, 10, 10, 10, 12, 13, 13])

In [50]:

t_E=np.transpose(E)


In [51]:
t_E

array([ 8,  8,  8, 10, 10, 10, 12, 13, 13])